data:
    name: 'distillation'
    image_dirs: [custom_dataset_road1/images]
    shuffle: false
    preprocessing:
        resize: [480, 640]
        grayscale: false
model:
    name: 'netvlad_original'
    image_channels: 3
weights: 'vd16_pitts30k_conv5_3_vlad_preL2_intra_white/vd16_pitts30k_conv5_3_vlad_preL2_intra_white'
