data:
    name: 'sfm'
    sequences: [
        'british_museum', 'florence_cathedral_side',
        'lincoln_memorial_statue', 'london_bridge',
        'milan_cathedral', 'mount_rushmore',
        'piazza_san_marco', 'reichstag', 'sagrada_familia',
        'st_pauls_cathedral', 'united_states_capitol']
    preprocessing:
        upright: true
model:
    name: 'super_point'
    nms_radius: 0
    detector_threshold: 0.005
    image_channels: 1
